version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nutrition_backend
    restart: always
    environment:
      - DATABASE_URL=sqlite:///data/database.db
    ports:
      - "8001:8001"
    volumes:
      - nutrition_data:/app/data

  frontend:
    build: ./mobile
    container_name: nutrition_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  nutrition_data:
